# shellcheck shell=bash
# PHASE 71 — final Bedrock configuration management.

BEDROCK_AOK_CONFIG=/bedrock/etc/bedrock.conf
BEDROCK_AOK_CONFIG_COMPAT=/bedrock/etc/brl

bedrock_aok_generate_config() {
    local arch manager
    bedrock_aok_require || return 1
    mkdir -p /bedrock/etc || return 1
    arch=$(uname -m 2>/dev/null || printf 'aarch64\n')
    case "$arch" in aarch64|arm64) arch=aarch64 ;; x86_64|amd64) arch=x86_64 ;; esac
    manager=systemd
    case "${INIT:-}" in openrc) manager=openrc ;; runit) manager=runit ;; sysvinit) manager=sysvinit ;; esac

    if [ -e "$BEDROCK_AOK_CONFIG" ]; then
        tui_msg "Bedrock config" "$BEDROCK_AOK_CONFIG already exists. Nothing was overwritten."
    else
        cat > "$BEDROCK_AOK_CONFIG" <<EOF
# Bedrock Linux configuration (generated by Systui)
# Canonical configuration used by: brl config get|set

[miscellaneous]
arch = $arch
color = true

[locale]
LANG = C.UTF-8

[cross]
enable = true
strict_integrity = true

[symlinks]
/etc/os-release = /bedrock/etc/os-release

[init]
manager = $manager
EOF
        chmod 0644 "$BEDROCK_AOK_CONFIG" 2>/dev/null || true
        log "bedrock-aok: generated $BEDROCK_AOK_CONFIG"
        tui_msg "Bedrock config generated" "Created $BEDROCK_AOK_CONFIG."
    fi

    # Compatibility path requested by Systui users. Upstream brl itself reads
    # /bedrock/etc/bedrock.conf; /bedrock/etc/brl points at the canonical file.
    if [ ! -e "$BEDROCK_AOK_CONFIG_COMPAT" ] && [ ! -L "$BEDROCK_AOK_CONFIG_COMPAT" ]; then
        ln -s bedrock.conf "$BEDROCK_AOK_CONFIG_COMPAT" 2>/dev/null || true
    fi
}

bedrock_aok_config_view() {
    bedrock_aok_require || return 1
    if [ ! -r "$BEDROCK_AOK_CONFIG" ]; then
        tui_msg "Bedrock config missing" "The canonical config $BEDROCK_AOK_CONFIG is missing. Use Generate config."
        return 0
    fi
    cp -f "$BEDROCK_AOK_CONFIG" "${SYSTUI_TMP:?}/bedrock-config" || return 1
    tui_text "Bedrock configuration" "$SYSTUI_TMP/bedrock-config"
}

bedrock_aok_config_edit() {
    bedrock_aok_require || return 1
    [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_generate_config || return 1
    "${EDITOR:-nano}" "$BEDROCK_AOK_CONFIG"
}

bedrock_aok_config_get_key() {
    local brl key
    brl=$(bedrock_aok_brl) || return 1
    key=$(tui_input "Bedrock config" "Config key (example: cross.strict_integrity):" "") || return 0
    [ -n "$key" ] || return 0
    run_cmd "Bedrock config get $key" "$brl" config get "$key"
}

bedrock_aok_config_set_key() {
    local brl key value
    brl=$(bedrock_aok_brl) || return 1
    [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_generate_config || return 1
    key=$(tui_input "Bedrock config" "Config key (example: cross.strict_integrity):" "") || return 0
    [ -n "$key" ] || return 0
    value=$(tui_input "Bedrock config" "Value for $key:" "") || return 0
    run_cmd "Bedrock config set $key" "$brl" config set "$key" "$value"
}

bedrock_aok_config_menu() {
    local c state
    bedrock_aok_require || return 0
    while true; do
        if [ -r "$BEDROCK_AOK_CONFIG" ]; then state=present; else state=missing; fi
        c=$(tui_menu "Bedrock-AOK configuration  [$state]" \
            "Canonical: $BEDROCK_AOK_CONFIG\nCompatibility: $BEDROCK_AOK_CONFIG_COMPAT" \
            generate "Generate config if missing" \
            view "View configuration" \
            edit "Edit configuration" \
            get "Read one config key" \
            set "Set one config key" \
            compat "Create /bedrock/etc/brl compatibility link" \
            back "Back") || return 0
        case "$c" in
            generate) bedrock_aok_generate_config ;;
            view) bedrock_aok_config_view ;;
            edit) bedrock_aok_config_edit ;;
            get) bedrock_aok_config_get_key ;;
            set) bedrock_aok_config_set_key ;;
            compat)
                mkdir -p /bedrock/etc || continue
                if [ -e "$BEDROCK_AOK_CONFIG_COMPAT" ] || [ -L "$BEDROCK_AOK_CONFIG_COMPAT" ]; then
                    tui_msg "Bedrock compatibility config" "$BEDROCK_AOK_CONFIG_COMPAT already exists."
                else
                    [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_generate_config || continue
                    ln -s bedrock.conf "$BEDROCK_AOK_CONFIG_COMPAT" && tui_msg "Bedrock compatibility config" "Created $BEDROCK_AOK_CONFIG_COMPAT -> bedrock.conf"
                fi
                ;;
            back|"") return 0 ;;
        esac
    done
}

return 0 2>/dev/null || true
