# shellcheck shell=bash
# PHASE 71 — final Bedrock configuration management.

BEDROCK_AOK_CONFIG=/bedrock/etc/bedrock.conf
BEDROCK_AOK_CONFIG_COMPAT=/bedrock/etc/brl

bedrock_aok_config_init_provider() {
    if declare -F systui_detect_init >/dev/null 2>&1; then
        systui_detect_init >/dev/null 2>&1 || true
    elif declare -F detect_init >/dev/null 2>&1; then
        detect_init >/dev/null 2>&1 || true
    fi
    case "${SYSTUI_INIT_PROVIDER:-${INIT:-}}" in
        systemd|ish-systemd-compat|systemd-offline) printf 'systemd\n' ;;
        openrc) printf 'openrc\n' ;;
        runit) printf 'runit\n' ;;
        sysvinit) printf 'sysvinit\n' ;;
        *) printf 'unknown\n' ;;
    esac
}

bedrock_aok_config_editor() {
    local editor=${EDITOR:-}
    if [ -n "$editor" ] && command -v "${editor%% *}" >/dev/null 2>&1; then
        printf '%s\n' "$editor"
    elif command -v nano >/dev/null 2>&1; then
        printf 'nano\n'
    elif command -v vi >/dev/null 2>&1; then
        printf 'vi\n'
    elif command -v vim >/dev/null 2>&1; then
        printf 'vim\n'
    else
        return 1
    fi
}

bedrock_aok_config_compat_state() {
    if [ -L "$BEDROCK_AOK_CONFIG_COMPAT" ]; then
        [ "$(readlink "$BEDROCK_AOK_CONFIG_COMPAT" 2>/dev/null || true)" = bedrock.conf ] && printf 'linked\n' || printf 'wrong-link\n'
    elif [ -e "$BEDROCK_AOK_CONFIG_COMPAT" ]; then
        printf 'regular-file\n'
    else
        printf 'missing\n'
    fi
}

bedrock_aok_config_write_default() {
    local arch manager
    mkdir -p /bedrock/etc || return 1
    [ -e "$BEDROCK_AOK_CONFIG" ] && return 0
    arch=$(uname -m 2>/dev/null || printf 'unknown\n')
    case "$arch" in aarch64|arm64) arch=aarch64 ;; x86_64|amd64) arch=x86_64 ;; esac
    manager=$(bedrock_aok_config_init_provider)
    cat > "$BEDROCK_AOK_CONFIG" <<EOF
# Bedrock Linux configuration (generated by Systui)
# Canonical configuration used by: brl config get|set

[miscellaneous]
arch = $arch
color = true

[locale]
LANG = C.UTF-8

[cross]
enable = true
strict_integrity = true

[symlinks]
/etc/os-release = /bedrock/etc/os-release

[init]
manager = $manager
EOF
    chmod 0644 "$BEDROCK_AOK_CONFIG" 2>/dev/null || true
    log "bedrock-aok: generated $BEDROCK_AOK_CONFIG"
}

# Normalize the historical /bedrock/etc/brl path. This function is deliberately
# idempotent and never calls bedrock_aok_generate_config(), avoiding recursive
# generate -> repair -> generate behavior and duplicate symlink creation.
bedrock_aok_config_repair_compat() {
    local state backup
    mkdir -p /bedrock/etc || return 1
    state=$(bedrock_aok_config_compat_state)
    case "$state" in
        linked)
            [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_config_write_default || return 1
            return 0
            ;;
        missing)
            [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_config_write_default || return 1
            ln -s bedrock.conf "$BEDROCK_AOK_CONFIG_COMPAT" || return 1
            ;;
        wrong-link)
            rm -f -- "$BEDROCK_AOK_CONFIG_COMPAT" || return 1
            [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_config_write_default || return 1
            ln -s bedrock.conf "$BEDROCK_AOK_CONFIG_COMPAT" || return 1
            ;;
        regular-file)
            if [ ! -e "$BEDROCK_AOK_CONFIG" ]; then
                mv "$BEDROCK_AOK_CONFIG_COMPAT" "$BEDROCK_AOK_CONFIG" || return 1
            else
                backup="${BEDROCK_AOK_CONFIG_COMPAT}.legacy.$(date +%Y%m%d%H%M%S)"
                mv "$BEDROCK_AOK_CONFIG_COMPAT" "$backup" || return 1
                log "bedrock-aok: preserved legacy /bedrock/etc/brl as $backup"
            fi
            ln -s bedrock.conf "$BEDROCK_AOK_CONFIG_COMPAT" || return 1
            ;;
        *) return 1 ;;
    esac
    return 0
}

# Every Bedrock config operation uses this preflight. Users should never need
# to manually repair the compatibility path before viewing/editing/getting or
# setting configuration.
bedrock_aok_config_preflight() {
    bedrock_aok_require || return 1
    mkdir -p /bedrock/etc || return 1
    [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_config_write_default || return 1
    bedrock_aok_config_repair_compat || {
        tui_msg "Bedrock config" "Could not normalize $BEDROCK_AOK_CONFIG_COMPAT. Check permissions under /bedrock/etc."
        return 1
    }
}

bedrock_aok_generate_config() {
    bedrock_aok_require || return 1
    if [ -e "$BEDROCK_AOK_CONFIG" ]; then
        bedrock_aok_config_repair_compat || return 1
        tui_msg "Bedrock config" "$BEDROCK_AOK_CONFIG already exists. Compatibility path is ready."
        return 0
    fi
    bedrock_aok_config_write_default || return 1
    bedrock_aok_config_repair_compat || return 1
    tui_msg "Bedrock config generated" "Created $BEDROCK_AOK_CONFIG and normalized $BEDROCK_AOK_CONFIG_COMPAT."
}

bedrock_aok_config_view() {
    bedrock_aok_config_preflight || return 1
    cp -f "$BEDROCK_AOK_CONFIG" "${SYSTUI_TMP:?}/bedrock-config" || return 1
    tui_text "Bedrock configuration" "$SYSTUI_TMP/bedrock-config"
}

bedrock_aok_config_edit() {
    local editor
    bedrock_aok_config_preflight || return 1
    editor=$(bedrock_aok_config_editor) || { tui_msg "Editor missing" "Install nano, vi, or vim, or set EDITOR."; return 1; }
    # shellcheck disable=SC2086
    $editor "$BEDROCK_AOK_CONFIG"
}

bedrock_aok_config_get_key() {
    local brl key
    bedrock_aok_config_preflight || return 1
    brl=$(bedrock_aok_brl) || return 1
    key=$(tui_input "Bedrock config" "Config key (example: cross.strict_integrity):" "") || return 0
    [ -n "$key" ] || return 0
    run_cmd "Bedrock config get $key" "$brl" config get "$key"
}

bedrock_aok_config_set_key() {
    local brl key value
    bedrock_aok_config_preflight || return 1
    brl=$(bedrock_aok_brl) || return 1
    key=$(tui_input "Bedrock config" "Config key (example: cross.strict_integrity):" "") || return 0
    [ -n "$key" ] || return 0
    value=$(tui_input "Bedrock config" "Value for $key:" "") || return 0
    run_cmd "Bedrock config set $key" "$brl" config set "$key" "$value"
}

bedrock_aok_config_menu() {
    local c state compat
    bedrock_aok_require || return 0
    # Repair is automatic on entry. Keep the manual action only as an advanced
    # recovery command, not a prerequisite for other menu operations.
    bedrock_aok_config_preflight || return 0
    while true; do
        if [ -r "$BEDROCK_AOK_CONFIG" ]; then state=present; else state=missing; fi
        compat=$(bedrock_aok_config_compat_state)
        c=$(tui_menu "Bedrock-AOK configuration  [$state]" \
            "Canonical: $BEDROCK_AOK_CONFIG\nCompatibility: $BEDROCK_AOK_CONFIG_COMPAT [$compat]" \
            view "View configuration" \
            edit "Edit configuration" \
            get "Read one config key" \
            set "Set one config key" \
            sync "Recheck/repair compatibility path" \
            back "Back") || return 0
        case "$c" in
            view) bedrock_aok_config_view ;;
            edit) bedrock_aok_config_edit ;;
            get) bedrock_aok_config_get_key ;;
            set) bedrock_aok_config_set_key ;;
            sync) bedrock_aok_config_preflight && tui_msg "Bedrock config" "Compatibility path is ready." ;;
            back|"") return 0 ;;
        esac
    done
}

return 0 2>/dev/null || true
