# shellcheck shell=bash
# PHASE 71 — final Bedrock configuration management.

BEDROCK_AOK_CONFIG=/bedrock/etc/bedrock.conf
BEDROCK_AOK_CONFIG_COMPAT=/bedrock/etc/brl

bedrock_aok_config_init_provider() {
    if declare -F systui_detect_init >/dev/null 2>&1; then
        systui_detect_init >/dev/null 2>&1 || true
    elif declare -F detect_init >/dev/null 2>&1; then
        detect_init >/dev/null 2>&1 || true
    fi
    case "${SYSTUI_INIT_PROVIDER:-${INIT:-}}" in
        systemd|ish-systemd-compat|systemd-offline) printf 'systemd\n' ;;
        openrc) printf 'openrc\n' ;;
        runit) printf 'runit\n' ;;
        sysvinit) printf 'sysvinit\n' ;;
        *) printf 'unknown\n' ;;
    esac
}

bedrock_aok_config_editor() {
    local editor=${EDITOR:-}
    if [ -n "$editor" ] && command -v "${editor%% *}" >/dev/null 2>&1; then
        printf '%s\n' "$editor"
    elif command -v nano >/dev/null 2>&1; then
        printf 'nano\n'
    elif command -v vi >/dev/null 2>&1; then
        printf 'vi\n'
    elif command -v vim >/dev/null 2>&1; then
        printf 'vim\n'
    else
        return 1
    fi
}

bedrock_aok_config_compat_state() {
    if [ -L "$BEDROCK_AOK_CONFIG_COMPAT" ]; then
        [ "$(readlink "$BEDROCK_AOK_CONFIG_COMPAT" 2>/dev/null || true)" = bedrock.conf ] && printf 'linked\n' || printf 'wrong-link\n'
    elif [ -e "$BEDROCK_AOK_CONFIG_COMPAT" ]; then
        printf 'regular-file\n'
    else
        printf 'missing\n'
    fi
}

bedrock_aok_config_repair_compat() {
    local state backup
    mkdir -p /bedrock/etc || return 1
    state=$(bedrock_aok_config_compat_state)
    case "$state" in
        linked) return 0 ;;
        missing|wrong-link)
            rm -f "$BEDROCK_AOK_CONFIG_COMPAT" 2>/dev/null || true
            [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_generate_config || return 1
            ln -s bedrock.conf "$BEDROCK_AOK_CONFIG_COMPAT"
            ;;
        regular-file)
            if [ ! -e "$BEDROCK_AOK_CONFIG" ]; then
                mv "$BEDROCK_AOK_CONFIG_COMPAT" "$BEDROCK_AOK_CONFIG" || return 1
            else
                backup="${BEDROCK_AOK_CONFIG_COMPAT}.legacy.$(date +%Y%m%d%H%M%S)"
                mv "$BEDROCK_AOK_CONFIG_COMPAT" "$backup" || return 1
                log "bedrock-aok: preserved legacy /bedrock/etc/brl as $backup"
            fi
            ln -s bedrock.conf "$BEDROCK_AOK_CONFIG_COMPAT"
            ;;
    esac
}

bedrock_aok_generate_config() {
    local arch manager
    bedrock_aok_require || return 1
    mkdir -p /bedrock/etc || return 1
    arch=$(uname -m 2>/dev/null || printf 'unknown\n')
    case "$arch" in aarch64|arm64) arch=aarch64 ;; x86_64|amd64) arch=x86_64 ;; esac
    manager=$(bedrock_aok_config_init_provider)

    if [ -e "$BEDROCK_AOK_CONFIG" ]; then
        tui_msg "Bedrock config" "$BEDROCK_AOK_CONFIG already exists. Nothing was overwritten."
    else
        cat > "$BEDROCK_AOK_CONFIG" <<EOF
# Bedrock Linux configuration (generated by Systui)
# Canonical configuration used by: brl config get|set

[miscellaneous]
arch = $arch
color = true

[locale]
LANG = C.UTF-8

[cross]
enable = true
strict_integrity = true

[symlinks]
/etc/os-release = /bedrock/etc/os-release

[init]
manager = $manager
EOF
        chmod 0644 "$BEDROCK_AOK_CONFIG" 2>/dev/null || true
        log "bedrock-aok: generated $BEDROCK_AOK_CONFIG"
        tui_msg "Bedrock config generated" "Created $BEDROCK_AOK_CONFIG."
    fi

    bedrock_aok_config_repair_compat || true
}

bedrock_aok_config_view() {
    bedrock_aok_require || return 1
    if [ ! -r "$BEDROCK_AOK_CONFIG" ]; then
        tui_msg "Bedrock config missing" "The canonical config $BEDROCK_AOK_CONFIG is missing. Use Generate config."
        return 0
    fi
    cp -f "$BEDROCK_AOK_CONFIG" "${SYSTUI_TMP:?}/bedrock-config" || return 1
    tui_text "Bedrock configuration" "$SYSTUI_TMP/bedrock-config"
}

bedrock_aok_config_edit() {
    local editor
    bedrock_aok_require || return 1
    [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_generate_config || return 1
    editor=$(bedrock_aok_config_editor) || { tui_msg "Editor missing" "Install nano, vi, or vim, or set EDITOR."; return 1; }
    # shellcheck disable=SC2086
    $editor "$BEDROCK_AOK_CONFIG"
}

bedrock_aok_config_get_key() {
    local brl key
    brl=$(bedrock_aok_brl) || return 1
    key=$(tui_input "Bedrock config" "Config key (example: cross.strict_integrity):" "") || return 0
    [ -n "$key" ] || return 0
    run_cmd "Bedrock config get $key" "$brl" config get "$key"
}

bedrock_aok_config_set_key() {
    local brl key value
    brl=$(bedrock_aok_brl) || return 1
    [ -e "$BEDROCK_AOK_CONFIG" ] || bedrock_aok_generate_config || return 1
    key=$(tui_input "Bedrock config" "Config key (example: cross.strict_integrity):" "") || return 0
    [ -n "$key" ] || return 0
    value=$(tui_input "Bedrock config" "Value for $key:" "") || return 0
    run_cmd "Bedrock config set $key" "$brl" config set "$key" "$value"
}

bedrock_aok_config_menu() {
    local c state compat
    bedrock_aok_require || return 0
    while true; do
        if [ -r "$BEDROCK_AOK_CONFIG" ]; then state=present; else state=missing; fi
        compat=$(bedrock_aok_config_compat_state)
        c=$(tui_menu "Bedrock-AOK configuration  [$state]" \
            "Canonical: $BEDROCK_AOK_CONFIG\nCompatibility: $BEDROCK_AOK_CONFIG_COMPAT [$compat]" \
            generate "Generate config if missing" \
            repair "Repair/migrate /bedrock/etc/brl compatibility path" \
            view "View configuration" \
            edit "Edit configuration" \
            get "Read one config key" \
            set "Set one config key" \
            back "Back") || return 0
        case "$c" in
            generate) bedrock_aok_generate_config ;;
            repair) bedrock_aok_config_repair_compat && tui_msg "Bedrock config" "Compatibility path repaired." ;;
            view) bedrock_aok_config_view ;;
            edit) bedrock_aok_config_edit ;;
            get) bedrock_aok_config_get_key ;;
            set) bedrock_aok_config_set_key ;;
            back|"") return 0 ;;
        esac
    done
}

return 0 2>/dev/null || true
