# shellcheck shell=bash
# PHASE 80 — final BusyBox rootfs init installation and selection.

if declare -F rootfs_wb_init_install_apt >/dev/null 2>&1 && ! declare -F _rootfs_wb_init_install_apt_before_busybox >/dev/null 2>&1; then
    eval "$(declare -f rootfs_wb_init_install_apt | sed '1s/^rootfs_wb_init_install_apt[[:space:]]*()/_rootfs_wb_init_install_apt_before_busybox ()/')"
fi

rootfs_wb_busybox_prepare() { # <target>
    local t="$1"
    mkdir -p "$t/etc" "$t/sbin" || return 1
    if [ ! -x "$t/bin/busybox" ] && [ ! -x "$t/usr/bin/busybox" ]; then
        return 1
    fi
    if [ ! -s "$t/etc/inittab" ]; then
        cat > "$t/etc/inittab" <<'EOF'
# BusyBox init configuration generated by Systui
::sysinit:/etc/init.d/rcS
::askfirst:-/bin/sh
::ctrlaltdel:/sbin/reboot
::shutdown:/bin/umount -a -r
EOF
    fi
    if [ ! -x "$t/etc/init.d/rcS" ]; then
        mkdir -p "$t/etc/init.d"
        cat > "$t/etc/init.d/rcS" <<'EOF'
#!/bin/sh
[ -d /proc ] && mountpoint -q /proc 2>/dev/null || mount -t proc proc /proc 2>/dev/null || true
[ -d /sys ] && mountpoint -q /sys 2>/dev/null || mount -t sysfs sysfs /sys 2>/dev/null || true
for s in /etc/init.d/S*; do
    [ -x "$s" ] || continue
    "$s" start 2>/dev/null || "$s" 2>/dev/null || true
done
exit 0
EOF
        chmod 0755 "$t/etc/init.d/rcS"
    fi
}

rootfs_wb_init_install_apt() { # <target> <init>
    local t="$1" init="$2" rc
    if [ "$init" != busybox ]; then
        _rootfs_wb_init_install_apt_before_busybox "$@"
        return $?
    fi
    rootfs_wb_ish_fix_dirs "$t" 2>/dev/null || mkdir -p "$t/proc" "$t/sys" "$t/dev" "$t/dev/pts" "$t/run" "$t/tmp"
    if declare -F rootfs_wb_init_mount_required >/dev/null 2>&1; then
        rootfs_wb_init_mount_required "$t" || return 1
    else
        rootfs_mount_chroot_fs "$t" || true
    fi
    rc=0
    systui_rootfs_exec "$t" sh -c 'export DEBIAN_FRONTEND=noninteractive; apt-get update && (apt-get install -y busybox-static || apt-get install -y busybox)' || rc=$?
    if declare -F rootfs_wb_init_unmount_required >/dev/null 2>&1; then rootfs_wb_init_unmount_required; fi
    [ "$rc" -eq 0 ] || return "$rc"
    rootfs_wb_busybox_prepare "$t"
}

if declare -F rootfs_wb_init_wire >/dev/null 2>&1 && ! declare -F _rootfs_wb_init_wire_before_busybox >/dev/null 2>&1; then
    eval "$(declare -f rootfs_wb_init_wire | sed '1s/^rootfs_wb_init_wire[[:space:]]*()/_rootfs_wb_init_wire_before_busybox ()/')"
fi
rootfs_wb_init_wire() { # <target> <init>
    local t="$1" init="$2" busy
    if [ "$init" != busybox ]; then _rootfs_wb_init_wire_before_busybox "$@"; return $?; fi
    rootfs_wb_busybox_prepare "$t" || return 1
    if [ -x "$t/bin/busybox" ]; then busy=/bin/busybox; else busy=/usr/bin/busybox; fi
    rm -f "$t/sbin/init"
    ln -s "$busy" "$t/sbin/init" || return 1
}

# Final rootfs init manager includes BusyBox as a selectable provider.
rootfs_wb_init_manager() { # <target>
    local t="$1" current c new
    while true; do
        current=$(rootfs_wb_init_detect "$t")
        c=$(tui_menu "Init system: $(basename "$t")" "Detected init: $current\n/sbin/init: $([ -x "$t/sbin/init" ] && echo ready || echo missing/broken)" \
            repair "Repair/reinstall current init ($current)" \
            replace "Replace current init system" \
            readiness "Run iSH-AOK boot readiness analyzer" \
            back "Back") || return 0
        case "$c" in
            repair)
                [ "$current" != unknown ] || { tui_msg "Init unknown" "Systui could not identify the current init. Use Replace current init system instead."; continue; }
                if [ "$current" = busybox ]; then
                    rootfs_wb_busybox_prepare "$t" && rootfs_wb_init_wire "$t" busybox
                else
                    rootfs_wb_init_repair "$t" "$current"
                fi
                ;;
            replace)
                new=$(tui_radio "Replace init system" "Select the new init system (SPACE selects):" \
                    systemd "systemd" "$(_rootfs_radio_state "$current" systemd)" \
                    runit "runit" "$(_rootfs_radio_state "$current" runit)" \
                    openrc "OpenRC" "$(_rootfs_radio_state "$current" openrc)" \
                    sysvinit "SysVinit" "$(_rootfs_radio_state "$current" sysvinit)" \
                    busybox "BusyBox init" "$(_rootfs_radio_state "$current" busybox)") || continue
                [ -n "$new" ] || continue
                [ "$new" = "$current" ] && { [ "$new" = busybox ] && rootfs_wb_busybox_prepare "$t" || rootfs_wb_init_repair "$t" "$current"; continue; }
                rootfs_wb_init_replace "$t" "$new" || true ;;
            readiness) rootfs_wb_ish_boot_analyze "$t" ;;
            back|'') return 0 ;;
        esac
    done
}

return 0 2>/dev/null || true
