# shellcheck shell=bash
###############################################################################
# ROOTFS BUILDER — iSH-AOK compatibility for systemd rootfs images
#
# systemd expects a number of Linux kernel facilities that iSH/iSH-AOK only
# partially implements. A systemd-selected rootfs should still keep genuine
# systemd for normal Linux, but when the image is booted under iSH-AOK its
# /sbin/init entry point needs a small compatibility supervisor instead of
# handing PID 1 directly to systemd.
###############################################################################

rootfs_install_ish_systemd_compat() { # <target>
    local t="$1" real_systemd init_path

    [ -d "$t" ] || return 1

    # Locate the real systemd binary inside the image. Keep it untouched; the
    # compatibility launcher execs it whenever the image is not running on iSH.
    for real_systemd in /lib/systemd/systemd /usr/lib/systemd/systemd; do
        [ -x "$t$real_systemd" ] && break
    done
    [ -x "$t$real_systemd" ] || {
        warn "systemd was selected, but no systemd binary exists in $t"
        return 0
    }

    mkdir -p "$t/usr/local/sbin" "$t/etc/systui" "$t/run" "$t/proc" "$t/sys" "$t/dev" "$t/dev/pts" "$t/tmp"

    cat > "$t/usr/local/sbin/systui-ish-init" <<EOF
#!/bin/sh
# Generated by systui. On a normal Linux kernel this immediately hands control
# to the distro's real systemd. On iSH/iSH-AOK it runs a lightweight PID 1
# compatibility supervisor because cgroups, namespaces, seccomp and several
# process-control interfaces required by systemd are only partially available.

REAL_SYSTEMD='$real_systemd'

is_ish_kernel() {
    k=\$(uname -r 2>/dev/null || true)
    v=\$(cat /proc/version 2>/dev/null || true)
    case "\$k \$v" in
        *-ish*|*ish_aok*|*iSH-AOK*|*iSH*) return 0 ;;
    esac
    [ -e /proc/ish ] && return 0
    return 1
}

if ! is_ish_kernel; then
    exec "\$REAL_SYSTEMD" "\$@"
fi

export container=ish-aok
export SYSTEMD_IN_CHROOT=1
export SYSTEMD_IGNORE_CHROOT=1
export SYSTEMD_LOG_TARGET=console
export SYSTEMD_LOG_LEVEL=warning
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

mkdir -p /run /run/lock /tmp /proc /sys /dev /dev/pts
chmod 1777 /tmp 2>/dev/null || true

# The host/chroot launcher often provides these already. Mount only when the
# kernel permits it, and never make failure fatal on iSH.
if command -v mountpoint >/dev/null 2>&1; then
    mountpoint -q /proc 2>/dev/null || mount -t proc proc /proc 2>/dev/null || true
    mountpoint -q /sys  2>/dev/null || mount -t sysfs sysfs /sys 2>/dev/null || true
    mountpoint -q /dev/pts 2>/dev/null || mount -t devpts devpts /dev/pts 2>/dev/null || true
fi

# systemd-compatible filesystem markers expected by many packages/services.
[ -e /etc/machine-id ] || : > /etc/machine-id
[ -s /etc/machine-id ] || {
    if command -v systemd-machine-id-setup >/dev/null 2>&1; then
        systemd-machine-id-setup >/dev/null 2>&1 || true
    elif command -v dbus-uuidgen >/dev/null 2>&1; then
        dbus-uuidgen --ensure=/etc/machine-id >/dev/null 2>&1 || true
    fi
}

[ -r /etc/hostname ] && hostname "\$(cat /etc/hostname)" 2>/dev/null || true

# Run traditional compatibility hooks when present. This lets packages with
# SysV scripts remain usable even though systemd itself cannot safely be PID 1.
for script in /etc/init.d/rcS /etc/rc.local; do
    [ -x "\$script" ] && "\$script" >/dev/console 2>&1 || true
done

# Start a conservative set of common daemons if their legacy launchers exist.
# Failures are ignored because an iSH rootfs may intentionally omit them.
for svc in dbus cron crond rsyslog ssh sshd networking network-manager; do
    if [ -x "/etc/init.d/\$svc" ]; then
        "/etc/init.d/\$svc" start >/dev/console 2>&1 || true
    fi
done

# Give the user a usable console while acting as PID 1. PID 1 must reap orphaned
# children, so keep a tiny supervisor loop around the interactive shell.
while :; do
    if [ -x /bin/bash ]; then
        /bin/bash -l
    else
        /bin/sh -l
    fi
    rc=\$?
    echo "iSH compatibility shell exited with status \$rc; restarting." >/dev/console 2>/dev/null || true
    sleep 1
done
EOF
    chmod 0755 "$t/usr/local/sbin/systui-ish-init"

    # Preserve the distro's original /sbin/init target for diagnostics and make
    # the compatibility launcher the public init entry point. The launcher
    # still executes real systemd unchanged on a normal Linux kernel.
    if [ -L "$t/sbin/init" ]; then
        init_path=$(readlink "$t/sbin/init" 2>/dev/null || true)
        printf '%s\n' "$init_path" > "$t/etc/systui/original-init"
        rm -f "$t/sbin/init"
    elif [ -e "$t/sbin/init" ]; then
        mv "$t/sbin/init" "$t/sbin/init.systui-original" 2>/dev/null || true
        printf '%s\n' /sbin/init.systui-original > "$t/etc/systui/original-init"
    fi
    ln -sfn /usr/local/sbin/systui-ish-init "$t/sbin/init"

    cat > "$t/etc/systui/ish-systemd-compat.conf" <<EOF
ENABLED=yes
REAL_SYSTEMD=$real_systemd
MODE=auto
DESCRIPTION=Use real systemd on normal Linux and the systui iSH PID1 compatibility supervisor on iSH-AOK.
EOF

    # Reduce boot-time assumptions made by systemd-aware packages when the same
    # image is inspected from inside iSH. These variables are harmless when the
    # compatibility launcher is not active.
    mkdir -p "$t/etc/profile.d"
    cat > "$t/etc/profile.d/systui-ish-systemd-compat.sh" <<'EOF'
case "$(uname -r 2>/dev/null) $(cat /proc/version 2>/dev/null)" in
    *-ish*|*ish_aok*|*iSH-AOK*|*iSH*)
        export container=ish-aok
        export SYSTEMD_IN_CHROOT=1
        ;;
esac
EOF
    chmod 0644 "$t/etc/profile.d/systui-ish-systemd-compat.sh"

    log "rootfs: installed iSH-AOK systemd compatibility layer in $t"
    return 0
}

# Preserve the canonical post-configuration implementation and augment it only
# for systemd-selected builds. Renaming only the function declaration avoids
# fragile body rewriting/eval transforms.
if declare -F rootfs_postconfig >/dev/null 2>&1 && \
   ! declare -F _systui_base_rootfs_postconfig >/dev/null 2>&1; then
    eval "$(declare -f rootfs_postconfig | sed '1s/^rootfs_postconfig[[:space:]]*()/_systui_base_rootfs_postconfig ()/')"
fi

rootfs_postconfig() {
    local target="$1" init_choice="$5" rc=0

    _systui_base_rootfs_postconfig "$@" || rc=$?
    [ "$rc" -eq 0 ] || return "$rc"

    if [ "$init_choice" = systemd ]; then
        rootfs_install_ish_systemd_compat "$target" || {
            warn "Could not install the iSH-AOK systemd compatibility layer."
            return 1
        }
    fi
    return 0
}

export -f rootfs_install_ish_systemd_compat rootfs_postconfig
